var courses =
    [
        {"id": 1001,
        "price": 1000,
        "name": "Bangla-Literature",
        "group": "All",
        "description": "NCTB Curriculam for SSC",
        "room": "R-101",
        "courseCoordinator": "Rabindranath Tagor",
        "courseGroupEmail": "bangla1.xyz@gmail.com",
        "url": "https://via.placeholder.com/150/92c952"},
        {"id": 1002,
        "price": 1000,
        "name": "Bangla-Grammar",
        "group": "All",
        "description": "NCTB Curriculam for SSC",
        "room": "R-201",
        "courseCoordinator": "Promath CHowdhury",
        "courseGroupEmail": "bangla2.xyz@gmail.com",
        "url": "https://via.placeholder.com/150/771796"},
        {"id": 1003,
        "price": 2000,
        "name": "Mathematics",
        "group": "All",
        "description": "NCTB Curriculam for SSC",
        "room": "R-102",
        "courseCoordinator": "Isaac Newton",
        "courseGroupEmail": "gmath.xyz@gmail.com",
        "url": "https://via.placeholder.com/150/24f355"},
        {"id": 1004,
        "price": 500,
        "name": "English",
        "group": "All",
        "description": "NCTB Curriculam for SSC",
        "room": "R-202",
        "courseCoordinator": "William Shakespeare",
        "courseGroupEmail": "english.xyz@gmail.com",
        "url": "https://via.placeholder.com/150/24f355"},
        {"id": 1005,
        "price": 1000,
        "name": "Physics",
        "group": "Science",
        "description": "NCTB Curriculam for SSC",
        "room": "R-302",
        "courseCoordinator": "Albert Einstein",
        "courseGroupEmail": "physics.xyz@gmail.com",
        "url": "https://via.placeholder.com/150/24f355"},
        {"id": 1006,
        "price": 1000,
        "name": "Biology",
        "group": "Science",
        "description": "NCTB Curriculam for SSC",
        "room": "L-101",
        "courseCoordinator": "Charles Darwin",
        "courseGroupEmail": "biology.xyz@gmail.com",
        "url": "https://randomuser.me/api/portraits/men/32.jpg"},
        {"id": 1007,
        "price": 1000,
        "name": "Chemistry",
        "group": "Science",
        "description": "NCTB Curriculam for SSC",
        "room": "L-301",
        "courseCoordinator": "Madam Marie Curie",
        "courseGroupEmail": "chemistry.xyz@gmail.com",
        "url": "https://randomuser.me/api/portraits/women/12.jpg"},
        {"id": 1008,
        "price": 5000,
        "name": "CSE",
        "group": "All",
        "description": "To be a computer gineous.",
        "room": "R-777",
        "courseCoordinator": "Jhankar Mahbub",
        "courseGroupEmail": "cse.xyz@gmail.com",
        "url": "https://randomuser.me/api/portraits/men/42.jpg"},
        {"id": 1009,
        "price": 1000,
        "name": "Accounting",
        "group": "Commerce",
        "description": "NCTB Curriculam for SSC",
        "room": "R-702",
        "courseCoordinator": "Luca Pacioli",
        "courseGroupEmail": "accounting.xyz@gmail.com",
        "url": "https://randomuser.me/api/portraits/women/53.jpg"},
        {"id": 1010,
        "price": 1000,
        "name": "Economics",
        "group": "Humanities",
        "description": "NCTB Curriculam for SSC",
        "room": "R-302",
        "courseCoordinator": "Karl Marx",
        "courseGroupEmail": "physics.xyz@gmail.com",
        "url": "https://randomuser.me/api/portraits/men/52.jpg"},
        {"id": 1011,
        "price": 1000,
        "name": "Psychology",
        "group": "Humanities",
        "description": "NCTB Curriculam for SSC",
        "room": "R-171",
        "courseCoordinator": "Sigmund Freud",
        "courseGroupEmail": "bangla1.xyz@gmail.com",
        "url": "https://randomuser.me/api/portraits/women/52.jpg"},
        {"id": 1012,
        "price": 1000,
        "name": "Finance",
        "group": "Commerce",
        "description": "NCTB Curriculam for SSC",
        "room": "R-231",
        "courseCoordinator": "Eugene F. Fama",
        "courseGroupEmail": "fin.xyz@gmail.com",
        "url": "https://via.placeholder.com/150/444796"},
        {"id": 1013,
        "price": 2000,
        "name": " Quantum Mechanics",
        "group": "All",
        "description": "NCTB Curriculam for SSC",
        "room": "R-102",
        "courseCoordinator": "Albert Einstein",
        "courseGroupEmail": "quantummech.xyz@gmail.com",
        "url": "https://via.placeholder.com/150/fdf73e"},
        {"id": 1014,
        "price": 500,
        "name": "Calculus",
        "group": "All",
        "description": "To be gineous.",
        "room": "R-242",
        "courseCoordinator": "Isaac Newton",
        "courseGroupEmail": "calculush.xyz@gmail.com",
        "url": "https://via.placeholder.com/150/51aa97"},
        {"id": 1015,
        "price": 5000,
        "name": "Algebra",
        "group": "All",
        "description": "To be gineous.",
        "room": "R-392",
        "courseCoordinator": "Muhammad ibn Musa al-Khwarizmi",
        "courseGroupEmail": "alzebra.xyz@gmail.com",
        "url": "https://via.placeholder.com/150/810b14"}
    ];
    export default courses;